module.exports={
    ecs1:{
        ip:'120.55.65.182',
        port:3306,
        db:{
            admin:{
                dbName:"admin",
                userName:"xianpu",
                pwd:"xianpuv587"
            },
            xp:{
                dbName:"xp",
                userName:"yjdz",
                pwd:"yjdztogetherv587"
            }
        }
    }
};